name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neo4j_version:
          - "4.4.38"
          - "5.1.0"
          - "5.2.0"
          - "5.3.0"
          - "5.4.0"
          - "5.5.0"
          - "5.6.0"
          - "5.7.0"
          - "5.8.0"
          - "5.9.0"
          - "5.10.0"
          - "5.11.0"
          - "5.12.0"
          - "5.13.0"
          - "5.14.0"
          - "5.15.0"
          - "5.16.0"
          - "5.17.0"
          - "5.18.1"
          - "5.19.0"
          - "5.20.0"
          - "5.21.2"
          - "5.22.0"
          - "5.23.0"
          - "5.24.2"
          - "5.25.1"
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --quiet --batch-mode verify
